### ISSUE TITLE
register this cookbook with supermarket.chef.io?

### ISSUE THREAD

**Issue by ffahimi** [wanelo-chef/manta#3]
As @bixu and I are implementing The Berkshelf Way (or at least trying it) at yetu, we'd like to have this cookbook and the manta-sync cookbook available via Supermarket.

Can you publish there?  For now we can hard-code our deps in our Berksfile.

**Comment by sax** [comment]
Done! I also made updated our license to MIT, which I think is more permissive of use.

**Comment by bixu** [comment]
Vielen dank!

**Comment by ffahimi** [comment]
Could you also please add manta-sync to supermarket? Thank you

**Comment by sax** [comment]
https://supermarket.chef.io/cookbooks/manta-sync

I didn't have much time to look at this one, so if you find any issues please open issues!

**Comment by ffahimi** [comment]
Thank you
